[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "." # This tells Netlify your index.html is in the root

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200